{% if theme.cnzz_siteid %}
<div style="display: none;">
<!-- 填写你的友盟代码 -->
<script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? "https://" : "http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1278301445'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "v1.cnzz.com/z_stat.php%3Fid%3D1278301445%26show%3Dpic' type='text/javascript'%3E%3C/script%3E"));</script>
<!-- 你的友盟代码 end -->
</div>
{% endif %}